services:
  fractal-worker:
    build:
      context: .
      network: host  
    deploy:
      replicas: 2
    ports:
      - "50051-50052:50051"
  grpcurl:
    image: fullstorydev/grpcurl
    profiles: ["tools"]